/// Godot project scaffolding — 3D (FPS) and 2D (platformer).
use std::path::PathBuf;
use tokio::fs;

pub async fn scaffold_3d(dir: &PathBuf, name: &str) -> Result<(), String> {
    // ── directory skeleton ────────────────────────────────────────────────────
    for sub in &[
        "assets/models",
        "assets/textures",
        "assets/materials",
        "assets/sounds",
        "assets/fonts",
        "scenes",
        "scripts",
    ] {
        fs::create_dir_all(dir.join(sub))
            .await
            .map_err(|e| e.to_string())?;
    }

    // ── project files ─────────────────────────────────────────────────────────
    write(dir, "project.godot", &project_godot_3d(name)).await?;
    write(dir, "scripts/player.gd", PLAYER_GD_3D).await?;
    write(dir, "scripts/game_manager.gd", GAME_MANAGER_GD).await?;
    write(dir, "scenes/main.tscn", MAIN_TSCN_3D).await?;

    Ok(())
}

pub async fn scaffold_2d(dir: &PathBuf, name: &str) -> Result<(), String> {
    for sub in &[
        "assets/sprites",
        "assets/textures",
        "assets/sounds",
        "assets/fonts",
        "scenes",
        "scripts",
    ] {
        fs::create_dir_all(dir.join(sub))
            .await
            .map_err(|e| e.to_string())?;
    }

    write(dir, "project.godot", &project_godot_2d(name)).await?;
    write(dir, "scripts/player.gd", PLAYER_GD_2D).await?;
    write(dir, "scripts/game_manager.gd", GAME_MANAGER_GD).await?;
    write(dir, "scenes/main.tscn", MAIN_TSCN_2D).await?;

    Ok(())
}

async fn write(dir: &PathBuf, rel: &str, content: &str) -> Result<(), String> {
    fs::write(dir.join(rel), content)
        .await
        .map_err(|e| format!("write {rel}: {e}"))
}

// ── project.godot ─────────────────────────────────────────────────────────────

fn project_godot_3d(name: &str) -> String {
    format!(
        r#"; Engine configuration file.
; Generated by file-mcp — open in Godot 4 to continue editing.

[application]

config/name="{name}"
config/features=PackedStringArray("4.2", "Forward Plus")
run/main_scene="res://scenes/main.tscn"
config/icon="res://icon.svg"

[autoload]

GameManager="*res://scripts/game_manager.gd"

[input]

move_forward={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":87,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
}}
move_back={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":83,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
}}
move_left={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":65,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
}}
move_right={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":68,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
}}
jump={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":32,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
}}

[rendering]

renderer/rendering_method="forward_plus"
"#
    )
}

fn project_godot_2d(name: &str) -> String {
    format!(
        r#"; Engine configuration file.
; Generated by file-mcp — open in Godot 4 to continue editing.

[application]

config/name="{name}"
config/features=PackedStringArray("4.2", "GL Compatibility")
run/main_scene="res://scenes/main.tscn"
config/icon="res://icon.svg"

[autoload]

GameManager="*res://scripts/game_manager.gd"

[input]

move_left={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":65,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
}}
move_right={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":68,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
}}
jump={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":32,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
}}

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
"#
    )
}

// ── scenes/main.tscn  (3D) ───────────────────────────────────────────────────
//
// Node tree:
//   Main (Node3D)
//   ├── WorldEnvironment        — ProceduralSky + ACES tonemapper
//   ├── DirectionalLight3D      — sun, shadow enabled
//   ├── Ground (StaticBody3D)   — 30×30 m flat plane
//   │   ├── GroundMesh
//   │   └── GroundCollision
//   ├── Cube (StaticBody3D)     — 1×1×1 m cube at (0, 0.5, -4)
//   │   ├── CubeMesh
//   │   └── CubeCollision
//   └── Player (CharacterBody3D) — FPS, spawns at (0, 1, 0)
//       ├── Camera3D            — eye height 1.6 m
//       └── PlayerCollision     — capsule r=0.4 h=1.8
//
// load_steps = ext_resources(1) + sub_resources(8) + 1 = 10

const MAIN_TSCN_3D: &str = r#"[gd_scene load_steps=10 format=3 uid="uid://c3d_main"]

[ext_resource type="Script" path="res://scripts/player.gd" id="1_player"]

[sub_resource type="ProceduralSkyMaterial" id="ProceduralSkyMaterial_1"]
sky_top_color = Color(0.15, 0.35, 0.75, 1)
sky_horizon_color = Color(0.65, 0.8, 1.0, 1)
sky_curve = 0.15
ground_bottom_color = Color(0.12, 0.09, 0.07, 1)
ground_horizon_color = Color(0.45, 0.48, 0.42, 1)
ground_curve = 0.02
sun_angle_max = 30.0
sun_curve = 0.15

[sub_resource type="Sky" id="Sky_1"]
sky_material = SubResource("ProceduralSkyMaterial_1")

[sub_resource type="Environment" id="Environment_1"]
background_mode = 2
sky = SubResource("Sky_1")
ambient_light_source = 3
ambient_light_color = Color(1, 1, 1, 1)
ambient_light_energy = 0.3
tonemap_mode = 2
glow_enabled = false

[sub_resource type="CapsuleShape3D" id="CapsuleShape3D_player"]
radius = 0.4
height = 1.8

[sub_resource type="BoxMesh" id="BoxMesh_cube"]
size = Vector3(1, 1, 1)

[sub_resource type="BoxShape3D" id="BoxShape3D_cube"]
size = Vector3(1, 1, 1)

[sub_resource type="BoxMesh" id="BoxMesh_ground"]
size = Vector3(30, 0.2, 30)

[sub_resource type="BoxShape3D" id="BoxShape3D_ground"]
size = Vector3(30, 0.2, 30)

[node name="Main" type="Node3D"]

[node name="WorldEnvironment" type="WorldEnvironment" parent="."]
environment = SubResource("Environment_1")

[node name="DirectionalLight3D" type="DirectionalLight3D" parent="."]
transform = Transform3D(0.866025, -0.433013, 0.25, 0, 0.5, 0.866025, -0.5, -0.75, 0.433013, 0, 10, 0)
light_energy = 1.2
shadow_enabled = true

[node name="Ground" type="StaticBody3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.1, 0)

[node name="GroundMesh" type="MeshInstance3D" parent="Ground"]
mesh = SubResource("BoxMesh_ground")
cast_shadow = 0

[node name="GroundCollision" type="CollisionShape3D" parent="Ground"]
shape = SubResource("BoxShape3D_ground")

[node name="Cube" type="StaticBody3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.5, -4)

[node name="CubeMesh" type="MeshInstance3D" parent="Cube"]
mesh = SubResource("BoxMesh_cube")

[node name="CubeCollision" type="CollisionShape3D" parent="Cube"]
shape = SubResource("BoxShape3D_cube")

[node name="Player" type="CharacterBody3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0)
script = ExtResource("1_player")

[node name="Camera3D" type="Camera3D" parent="Player"]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1.6, 0)
current = true

[node name="PlayerCollision" type="CollisionShape3D" parent="Player"]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.9, 0)
shape = SubResource("CapsuleShape3D_player")
"#;

// ── scenes/main.tscn  (2D) ───────────────────────────────────────────────────
//
// Node tree:
//   Main (Node2D)
//   ├── Background (ColorRect)  — sky-blue fill, z=-10
//   ├── Ground (StaticBody2D)   — 1280×40 px platform at y=700
//   │   ├── GroundShape
//   │   └── GroundVis (ColorRect)
//   └── Player (CharacterBody2D) — 32×64 px rectangle, spawns at (200, 600)
//       ├── CollisionShape2D
//       ├── Sprite (ColorRect)
//       └── Camera2D            — follows the player
//
// load_steps = ext_resources(1) + sub_resources(2) + 1 = 4

const MAIN_TSCN_2D: &str = r#"[gd_scene load_steps=4 format=3 uid="uid://c2d_main"]

[ext_resource type="Script" path="res://scripts/player.gd" id="1_player"]

[sub_resource type="RectangleShape2D" id="RectangleShape2D_player"]
size = Vector2(32, 64)

[sub_resource type="RectangleShape2D" id="RectangleShape2D_ground"]
size = Vector2(1280, 40)

[node name="Main" type="Node2D"]

[node name="Background" type="ColorRect" parent="."]
offset_left = 0.0
offset_top = 0.0
offset_right = 1280.0
offset_bottom = 720.0
color = Color(0.18, 0.45, 0.78, 1)
z_index = -10

[node name="Ground" type="StaticBody2D" parent="."]
position = Vector2(640, 700)

[node name="GroundShape" type="CollisionShape2D" parent="Ground"]
shape = SubResource("RectangleShape2D_ground")

[node name="GroundVis" type="ColorRect" parent="Ground"]
offset_left = -640.0
offset_top = -20.0
offset_right = 640.0
offset_bottom = 20.0
color = Color(0.28, 0.58, 0.22, 1)

[node name="Player" type="CharacterBody2D" parent="."]
position = Vector2(200, 600)
script = ExtResource("1_player")

[node name="CollisionShape2D" type="CollisionShape2D" parent="Player"]
shape = SubResource("RectangleShape2D_player")

[node name="Sprite" type="ColorRect" parent="Player"]
offset_left = -16.0
offset_top = -64.0
offset_right = 16.0
offset_bottom = 0.0
color = Color(0.9, 0.38, 0.18, 1)

[node name="Camera2D" type="Camera2D" parent="Player"]
zoom = Vector2(1, 1)
"#;

// ── scripts/player.gd (3D FPS) ───────────────────────────────────────────────

const PLAYER_GD_3D: &str = r#"extends CharacterBody3D

const SPEED           := 5.0
const JUMP_VELOCITY   := 4.5
const MOUSE_SENSITIVITY := 0.003
const MAX_LOOK_ANGLE  := 80.0   # degrees, clamped to avoid gimbal flip

@onready var _camera: Camera3D = $Camera3D

func _ready() -> void:
    Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

func _unhandled_input(event: InputEvent) -> void:
    if event is InputEventMouseMotion and \
            Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:
        # Horizontal look — rotate the whole body.
        rotate_y(-event.relative.x * MOUSE_SENSITIVITY)
        # Vertical look — tilt the camera only.
        _camera.rotate_x(-event.relative.y * MOUSE_SENSITIVITY)
        _camera.rotation.x = clamp(
            _camera.rotation.x,
            -deg_to_rad(MAX_LOOK_ANGLE),
             deg_to_rad(MAX_LOOK_ANGLE)
        )

func _physics_process(delta: float) -> void:
    # Gravity
    if not is_on_floor():
        velocity += get_gravity() * delta

    # Jump
    if Input.is_action_just_pressed("jump") and is_on_floor():
        velocity.y = JUMP_VELOCITY

    # Horizontal movement in the direction the camera faces.
    var input_dir := Input.get_vector(
        "move_left", "move_right", "move_forward", "move_back"
    )
    var direction := (
        transform.basis * Vector3(input_dir.x, 0, input_dir.y)
    ).normalized()

    if direction:
        velocity.x = direction.x * SPEED
        velocity.z = direction.z * SPEED
    else:
        velocity.x = move_toward(velocity.x, 0, SPEED)
        velocity.z = move_toward(velocity.z, 0, SPEED)

    move_and_slide()
"#;

// ── scripts/player.gd (2D platformer) ────────────────────────────────────────

const PLAYER_GD_2D: &str = r#"extends CharacterBody2D

const SPEED         := 200.0
const JUMP_VELOCITY := -420.0
const GRAVITY       := 980.0    # pixels/s², overrides project gravity if set

func _physics_process(delta: float) -> void:
    # Gravity
    if not is_on_floor():
        velocity.y += GRAVITY * delta

    # Jump
    if Input.is_action_just_pressed("jump") and is_on_floor():
        velocity.y = JUMP_VELOCITY

    # Horizontal movement
    var dir := Input.get_axis("move_left", "move_right")
    if dir != 0:
        velocity.x = dir * SPEED
    else:
        velocity.x = move_toward(velocity.x, 0, SPEED)

    move_and_slide()
"#;

// ── scripts/game_manager.gd ───────────────────────────────────────────────────

const GAME_MANAGER_GD: &str = r#"## GameManager — autoloaded singleton.
## Add global game state, scoring, scene transitions, etc. here.
extends Node

func _ready() -> void:
    pass
"#;

// ── .gitignore for Godot ──────────────────────────────────────────────────────

pub const GITIGNORE: &str = "# Godot cache and imported assets\n.godot/\n*.import\n*.translation\n\n# Export configs (may contain signing keys)\nexport_presets.cfg\n\n# macOS\n.DS_Store\n";
